acc/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from employee_learning.views import CourseDetail


app_name = "acc"
urlpatterns = [
    # previous login url
    # path('login/', views.user_login, name="login"),

    # login/logout urls
    # url-адреса входа и выхода
    path('test-function/', views.function_view_test),
    path('test-class/', views.ClassViewTest.as_view()),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    # path('course-detail/<int:pk>/', CourseDetail.as_view(), name='course_detail'),
    
    

    # # URL-адреса для смены пароля
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(),
    #      name='password_change'),
    # # URL-адреса для сброса пароля
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('password-reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(),
    #      name='password_reset_confirm'),
    # path('password-reset/complete/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),

    
]

employee_learning/urls.py
from django.urls import path, reverse
from .views import CourseList, CourseDetail, CourseCreate, CourseUpdate,  CourseDelete 
from .views import Index
app_name='employee_learning'

urlpatterns = [
    #  path('kebab-case/' , PascalCase.as_view() ,  name="'snake_case')
    path('', Index.as_view(), name='index'),
    path('course-list/', CourseList.as_view(), name='course_list'),
    path('course-detail/<int:pk>/', CourseDetail.as_view(), name='course_detail'),
    path('course-create/', CourseCreate.as_view(), name='course_create'),
    path('course-update/<int:pk>/', CourseUpdate.as_view(), name='course_update'),
    path('course-delete/<int:pk>/', CourseDelete.as_view(), name='course_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('acc/', include("acc.urls")),
    path('polls/', include("polls.urls")),
    # path('employee-learning/', include('employee_learning.urls')),
    path('', include('employee_learning.urls')),
    # path('social-auth/', 
    #     include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include("debug_toolbar.urls"))
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

employee_learning/models.py
import datetime
from django.db import models
from django.urls import reverse

class Division(models.Model):
    div_name = models.CharField(max_length=25)
    in_scope = models.BooleanField(
        help_text="If the division is target for the learning program, check this field.")


    def __str__(self):
        return self.div_name


class Employee(models.Model):
    PRIORITIES = [('H', 'High'), ('M', 'Medium'), ('L', 'Low'),]
    name = models.CharField(max_length=25, verbose_name="Employee Name")
    priority = models.CharField(max_length=1, 
                                verbose_name="Learning Priorities", 
                                choices=PRIORITIES, default='M')
    reg_date = models.DateField(default=datetime.date.today, 
                                              verbose_name="Data registration Date")
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class PersonalInfo(models.Model):
    name = models.OneToOneField(Employee, 
            on_delete=models.CASCADE, primary_key=True)
    tel = models.CharField(max_length=15)
    address = models.CharField(max_length=50)


    def __str__(self):
        return self.name #, self.tel, self.address

class LearningCourse(models.Model):
    LEVEL = [('B', 'Basic'), ('I', 'Intermediate'), ('A', 'Advanced'),]
    title = models.CharField(max_length=50, unique=True)
    level = models.CharField(max_length=1, choices=LEVEL)
    employee = models.ManyToManyField(Employee)


    def __str__(self) -> str:
        return self.title

employee_learning/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .models import LearningCourse
from django.urls import reverse_lazy
import datetime


class CourseList(ListView):
    # model = LearningCourse
    # queryset = LearningCourse.objects.order_by('title')
    queryset = LearningCourse.objects.filter(level='B')
    template_name = 'employee_learning/course_list.html'
    # Извлекает список объектов из базы данных
    context_object_name = 'course_object_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = datetime.date.today()
        return context


class CourseDetail(DetailView):
    model = LearningCourse
    template_name = 'employee_learning/course_detail.html'
    # извлекает один объект из базы данных модели 
    context_object_name = 'course_object'



class CourseCreate(CreateView):
    model = LearningCourse
    template_name = 'employee_learning/course_create.html'
    fields = ('title', 'level', 'employee')
    success_url = reverse_lazy('employee_learning:course_list')


class CourseUpdate(UpdateView):
    model = LearningCourse
    template_name = 'employee_learning/course_update.html'
    fields = ('title', 'level', 'employee')
    success_url = reverse_lazy('employee_learning:course_list')


class CourseDelete(DeleteView):
    model = LearningCourse
    template_name = 'employee_learning/course_delete.html'
    fields = ('title', 'level', 'employee')
    success_url = reverse_lazy('employee_learning:course_list')


class Index(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = datetime.data.today()
        return context

employee_learning/templates/employee_learning/course_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

{% comment %} <a href="{% url 'employee_learning:course_list' %}">List</a>
<a href="{% url 'employee_learning:course_create' %}">Create</a> {% endcomment %}
<h1>CREATE Page</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

employee_learning/templates/employee_learning/course_delete.html
<h1>DELETE Page</h1>

<form metod="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete "{{ object }}"?
    </p>
    <input type="submit" value="Confirm">
</form>

employee_learning/templates/employee_learning/course_detail.html
{% extends "base.html" %}

{% block title %}{% endblock %}
{% block content %}
<h1>DETAIL Page</h1>
<p>Course title : {{ course_object.title|upper }}</p>
<p>Level : {{ course_object.get_level_display }}</p>

<p>Assigned Employees : </p>

{% for emp in object.employee.all  %}
<p>{{ emp.name }} : {{ emp.division }}</p>
{% endfor %}


<a href="{% url 'employee_learning:course_update' object.pk%}">Update</a>
<a href="{% url 'employee_learning:course_delete' object.pk%}">Delete</a>
{% endblock %}

employee_learning/templates/employee_learning/course_list.html
{% extends "base.html" %}

{% block title %}<h1>LIST page</h1>{% endblock %}

{% block content %}
<h1 class="text-center mt-5">LIST page</h1>
<p class="text-muted test-center mb-5">As of {{ today }}</p>
{% for course in object_list %}
<p>{{ course.title|upper }}</p>
<p>{{ course.get_level_display }}</p>
<a href="{% url 'employee_learning:course_detail' course.pk %}">Go
    Detail</a>
<hr>
{% endfor %}

{% endblock %}

employee_learning/templates/employee_learning/course_update.html
<h1>UPDATE Page</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" valeu="Save">
</form>