acc/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from employee_learning.views import CourseDetail


app_name = "acc"
urlpatterns = [
    # previous login url
    # path('login/', views.user_login, name="login"),

    # login/logout urls
    # url-адреса входа и выхода
    path('test-function/', views.function_view_test),
    path('test-class/', views.ClassViewTest.as_view()),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    # path('course-detail/<int:pk>/', CourseDetail.as_view(), name='course_detail'),
    
    

    # # URL-адреса для смены пароля
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(),
    #      name='password_change'),
    # # URL-адреса для сброса пароля
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('password-reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(),
    #      name='password_reset_confirm'),
    # path('password-reset/complete/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),

    
]

account/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from employee_learning.views import CourseDetail


app_name = "account"
urlpatterns = [
    # previous login url
    # path('login/', views.user_login, name="login"),

    # login/logout urls
    # url-адреса входа и выхода
    path('test-function/', views.function_view_test),
    path('test-class/', views.ClassViewTest.as_view()),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    
    

    # # URL-адреса для смены пароля
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(),
    #      name='password_change'),
    # # URL-адреса для сброса пароля
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('password-reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(),
    #      name='password_reset_confirm'),
    # path('password-reset/complete/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),

    
]

employee_learning/urls.py
from django.urls import path, reverse
from .views import CourseList, CourseDetail, CourseCreate, CourseUpdate,  CourseDelete 
from .views import Index
app_name='employee_learning'

urlpatterns = [
    #  path('kebab-case/' , PascalCase.as_view() ,  name="'snake_case')
    path('', Index.as_view(), name='index'),
    path('course-list/', CourseList.as_view(), name='course_list'),
    path('course-detail/<int:pk>/', CourseDetail.as_view(), name='course_detail'),
    path('course-create/', CourseCreate.as_view(), name='course_create'),
    path('course-update/<int:pk>/', CourseUpdate.as_view(), name='course_update'),
    path('course-delete/<int:pk>/', CourseDelete.as_view(), name='course_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('acc/', include("acc.urls")),
    path('polls/', include("polls.urls")),
    # path('employee-learning/', include('employee_learning.urls')),
    path('', include('employee_learning.urls')),
    # path('social-auth/', 
    #     include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include("debug_toolbar.urls"))
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

acc/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    """
    Модель профиль пользователя
    attr:
        user,
        date-of_birth,
        photo
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(
        upload_to='users/%Y/%m/%d/',
        blank=True
    )
    def __str__(self) -> str:
        return f'Profile of {self.user.username}'


# class AbstractUser(User):
#     pass

acc/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User
# from django.contrib.auth import get_user_model
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    """Форма регистрации пользователя"""
    password = forms.CharField(label="Password",
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                               widget=forms.PasswordInput)

    class Meta:
        model = User
        # model = get_user_model()
        fields = ['username','first_name', 'email']


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t math.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        # exist() Метод возвращает True, если набор запросов QuerySet 
        # содержит какие-либо результаты, и False в противном случае
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already in use.')
        return data 


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(
            id=self.instance.id
        ).filter(
            email=data
        )
        if qs.exists():
            raise forms.ValidationError('Email already in use.')
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']

acc/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, \
                    UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib import messages

from django.views.generic import TemplateView


def user_login(request):
    # Если метод запроса Пост
    if request.method == 'POST':
        # создаем пустую форму
        form = LoginForm(request.POST)
        # Проверяем валидность формы
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard'})
    

def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            #Создать новый объект пользователя,
            # но пока не сохранять его
            new_user = user_form.save(commit=False)
            # Установить выбранный пароль
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Сохранить объект User
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            return render(request,
                          'account/register_done.html', 
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, 
                                 data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile update'\
                'successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(
                                instance=request.user.profile)
    return render(request, 
                  'account/edit.html',
                {'user_form': user_form,
                 'profile_form': profile_form})
    


def function_view_test(request):
    return HttpResponse('<h1>Hello world! Function-based ViewTest</h1>')


class ClassViewTest(TemplateView):
    template_name = 'account/test.html'

acc/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Employee Learning{% endblock %}</title>
<link href="{% static "css/base.css" %}" rel="stylesheet">
{% include "css_link.html" %}
</head>
<body>
    {% include "navbar.html" %}
<div id="header">
{% if request.user.is_authenticated %}
<ul class="menu">
    {% comment %} <li>
        <a href="{% url 'polls:index' %}" >
        <img style="padding: auto;" src="/media/logo/logopolls.png" weight="50" height="50" alt="Polls">
        Polls</a>
    </li> {% endcomment %}
<li {% if section == "dashboard" %}class="selected"{% endif %}>
<a href="{% url "account:dashboard" %}">My dashboard</a>
</li>
<li {% if section == "mypolls" %}class="selected"{% endif %}>
    <a href="{% url 'polls:index' %}">My polls</a>
</li>
<li {% if section == "сourses" %}class="selected"{% endif %}>
    <a href="{% url "employee_learning:course_list" %}">Courses</a>
</li>
<li {% if section == "images" %}class="selected"{% endif %}>
<a href="#">Images</a>
</li>
<li {% if section == "create" %}class="selected"{% endif %}>
<a href="{% url "employee_learning:course_create" %}">Create page</a>
</li>
<li {% if section == "detail" %}class="selected"{% endif %}>
    <a href="#">Detail</a>
    {% comment %} <a href="{% url "employee_learning:course_detail" course_object.pk??? pk=object.id %}">Details</a> {% endcomment %}
    </li>
    <li {% if section == "update" %}class="selected"{% endif %}>
        <a href="#">Update</a>
        {% comment %} <a href="{% url "employee_learning:course_update" object.pk %}">Update</a> {% endcomment %}
    </li>
    <li {% if section == "delite" %}class="selected"{% endif %}>
        <a href="#">Delete</a>
        {% comment %} <a href="{% url "employee_learning:course_update" object.pk %}">Update</a> {% endcomment %}
    </li>
</ul>
{% endif %}
<span class="user">
{% if request.user.is_authenticated %}
Hello {{ request.user.first_name|default:request.user.username }},
<form action="{% url "account:logout" %}" method="post"></a>
    <button type="submit">Logout</button>
    {% csrf_token %}
</form>
{% else %}
<a href="{% url "account:login" %}">Log-in</a>
{% endif %}
</span>
</div>
</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">x</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<div id="content">
<a href="{% url 'employee_learning:course_list'%}">List</a>
<a href="{% url 'employee_learning:course_create'%}">Create</a>
{% block content %}
{% endblock %}
</div>
</body>
{% block footer %}
<div class="container">
<hr>
    <div id="dno"  style="background:#12c064">
                <img style="padding: 10px 5px;" src="/media/logo/logopolls.png" width="50" alt="Polls">
    <p style=" padding: 5px; ">Design & Development</p>
    {% comment %} <h5 style="text-align: center;">Disign & Development</h5> {% endcomment %}
    </div>
</div>
{% endblock %}
<h6>2023 Employee Learning</h6>
</html>

acc/templates/css_link.html
<link
href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0
-alpha2/....>

acc/templates/footer.html
<h6 class="text-muted text-center mt-5"
style="font-size:0.8rem">2024 Employee
Learning</h6>
<script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-
alpha2/...."></script>

acc/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-
tertiary">
<div class="container-fluid">
</div>
</nav>